services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
  server:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - server
